title = "Adam Warski"
author = "Adam Warski"
name = "Adam Warski"
stars = 5

################ Social ##################
[[social]]
title = "twitter"
icon = "fa-brands fa-x-twitter" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "linkedin"
icon = "fa-brands fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "facebook"
icon = "fa-brands fa-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "github"
icon = "fa-brands fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "dribbble"
icon = "fa-brands fa-dribbble" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"
